### ISSUE TITLE
nupic for htmengine

### ISSUE THREAD

**Issue by scaviator** [numenta/nupic#3848]
Hello,

I'm trying to install htmengine with nupic 1.0.6; however, the htmengine installer errors out and complains that it can't find a compatible version of nupic.  According to htmengine's requirement file, it requires nupic 0.3.4; however, that is extremely old.  I tried installing nupic 0.3.4; however, it error out saying that it couldn't find a compatible version of nupic.bindings.

Any guidance on this would be greatly appreciated.  Thx.

**Comment by rhyolight** [comment]
Hi. I'm going to close this issue because it is an htm engine issue, not a nupic one. I'll open a ticket there if one does not already exist and cite this ticket.

**Comment by rhyolight** [comment]
So there is no issue tracker there because it is in maintenance mode. We have no current plans to upgrade HTM Engine to use a more recent NuPIC version. You or someone in the HTM community would have to do the work to upgrade to a newer version. There are some instructions on upgrading on [HTM Forum](https://discourse.numenta.org/search?q=breaking%20changes%20nupic). Sorry I'm not more help, but we have stopped working on applications and are completely focused on sensory-motor research with HTM and grid cells for object recognition.

**Comment by scaviator** [comment]
Thanks for the feedback.  I'm happy to look into upgrading the htm engine to use a more recent NuPIC.  You references the HTM Forum.  Is there something specific I should look for?  I'm not very familiar with how the HTM engine was built.  Do I just recompile it with a newer NuPIC?  I'm just trying to get a sense of how involved it is to upgrade the htmengine.  If it's too involved, I may just take a different route.  Thx.

**Comment by rhyolight** [comment]
The link I gave above as a search for the breaking changes. The main thinks you'll have to change in HTM Engine should be mostly encompassed in this post: https://discourse.numenta.org/t/warning-0-7-0-breaking-changes/2200

**Comment by scaviator** [comment]
Thanks for the pointers.  I updated everything noted in your post and was able to install htmengine with nupic 1.0.6.dev0.  However, when I check my supervisor, one of the services didn't start.

htmengine:metric_storer

![image](https://user-images.githubusercontent.com/28540780/42491896-a8428222-83cb-11e8-9bd6-736fa6279131.png)

Looking at the error, it looks like there is an issue with fieldmeta.


fieldmeta
ImportError: cannot import name fieldmeta
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/afang/.local/lib/python2.7/site-packages/htmengine/runtime/metric_storer.py", line 42, in <module>
    from htmengine.adapters.datasource import createCustomDatasourceAdapter
  File "/home/afang/.local/lib/python2.7/site-packages/htmengine/adapters/datasource/__init__.py", line 22, in <module>
    import htmengine.adapters.datasource.custom
  File "/home/afang/.local/lib/python2.7/site-packages/htmengine/adapters/datasource/custom/__init__.py", line 37, in <module>
    from htmengine.runtime import scalar_metric_utils
  File "/home/afang/.local/lib/python2.7/site-packages/htmengine/runtime/scalar_metric_utils.py", line 38, in <module>
    from nupic.data import fieldmeta
ImportError: cannot import name fieldmeta

**Comment by rhyolight** [comment]
Here is a list of the major breaking changes between you'll need to review to make NuPIC 1+ work with HTM Engine: https://discourse.numenta.org/t/warning-0-7-0-breaking-changes/2200

**Comment by scaviator** [comment]
Thanks.  I  went through the changes noted in post.  Everything seems to be fine except for the following import.

The system can't seem to import the following:

> from nupic.data import fieldmeta

Does fieldmeta exist in nupic.data for nupic version 1+

**Comment by rhyolight** [comment]
try `field_meta`

**Comment by scaviator** [comment]
Thanks!  The field_meta did the trick.  I got it working htmegine working with nupic 1.0.6 now.
