### ISSUE TITLE
pip install nupic ERROR "No distributions at all found for nupic.bindings==0.2.1 (from nupic)"

### ISSUE THREAD

**Issue by poshlf** [numenta/nupic#2651]
Hello,
currently I'm trying to install nupic on a Debian machine (virtual machine - the version of the os is "debian-8.2.0-amd64").

After having installed `pip` I launched the install command `pip install nupic` obtaining the error shown in the attached pic.

I took vision of old issue topics and of the failure log. However still I'm not able to resolve the problem.

![debain_nupic_install_error](https://cloud.githubusercontent.com/assets/15036808/10374154/d511bb9e-6df1-11e5-8d21-3593c94d48f1.png)

**Comment by rhyolight** [comment]
On a Debian machine, you cannot install simply with `pip install nupic`. Please see: https://github.com/numenta/nupic#install-linux

You may need to compile from scratch on Debian, I have not tried out the binary for Linux there. It was build on Ubuntu.

**Comment by rhyolight** [comment]
This may help you: 

[![Installing](http://img.youtube.com/vi/1fIpgXHXAZA/0.jpg)](http://www.youtube.com/watch?v=1fIpgXHXAZA)

[![Compiling](http://img.youtube.com/vi/BrnPQJKpcWo/0.jpg)](http://www.youtube.com/watch?v=BrnPQJKpcWo)

**Comment by poshlf** [comment]
First of all thank you very much for the reply. Second, I watched the video about installing nupic on Ubuntu. In order to compile nupic directly on debian I have to follow the guide (https://github.com/numenta/nupic/wiki/Installing-and-Building-NuPIC - Installation from Source Code) and watch the second video?

**Comment by rhyolight** [comment]
Correct, but it probably won't work exactly correct for Debian. I've been
asked to create a video for compilation / installation on a Debian system,
but I haven't had the time yet.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by poshlf** [comment]
I see. Could you please provide me an alternative linux OS (without graphical interface) which nupic can work correctly? I need to use nupic on a OS that is not equipped with GUI (I do not think ubuntu can be installed without GUI).

**Comment by rhyolight** [comment]
Thanks for the report!

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by poshlf** [comment]
Hello again,
I managed to install ubuntu (os version is "Ubuntu 15.04 "Vivid Vervet" minimal - https://help.ubuntu.com/community/Installation/MinimalCD). Even after executing with success the previously steps shown in the installation video on ubuntu, after launching the command 'pip install nupic --user' I'm facing the error 'No distributions at all found for nupic.bindings==0.2.2 (from nupic)' (please note that this time is 0.2.2. not 0.2.1).

**Comment by breznak** [comment]
Readme is your friend! https://github.com/numenta/nupic

It mentions for linux you can't install nupic.bindings from pip directly,
but just have to use another command

**Comment by poshlf** [comment]
As wrote in the read me and shown in the video I executed first `pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.2.2-cp27-none-linux_x86_64.whl` and then `pip install nupic`

**Comment by rhyolight** [comment]
@poshlf What is the console output when you run `pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.2.2-cp27-none-linux_x86_64.whl`?

**Comment by poshlf** [comment]
Now I understand what was the problem. For all the attempts I always followed the video that shown the usage of `nupic.bindings-0.2.1` rather than `nupic.bindings-0.2.2`.. I finally managed to install nupic. Thank you.

However, trying to test it (after of course after exporting the nupic variable and after installing the required  `python-pytest` and `python-pytest-xdist`) I get only errors after the test is completed (you can see some of them shown in the attached pic).

![schermata 2015-10-09 alle 01 18 50](https://cloud.githubusercontent.com/assets/15036808/10382392/cd951faa-6e23-11e5-908e-3f42ed2bf5be.png)

**Comment by rhyolight** [comment]
If you want to run tests, you'll need to install more python packages. I
suggest you watch the other video on compiling NuPIC, which contains those
instructions.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by wishingwei** [comment]
@poshlf @rhyolight 
sorry to bother, but I have run into this problem too, when running the following (as you noted above, mine is nupic.bindings -0.2.2)

pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.2.2-cp27-none-linux_x86_64.whl --user

and got this error info:

Downloading/unpacking nupic.bindings==0.2.2 (from nupic)
  Could not find any downloads that satisfy the requirement nupic.bindings==0.2.2 (from nupic)
  Some externally hosted files were ignored (use --allow-external nupic.bindings to allow).
Cleaning up...
No distributions at all found for nupic.bindings==0.2.2 (from nupic)

Could you tell me, how did you finally secceed?

**Comment by rhyolight** [comment]
@wishingwei What version of pip are you using? `pip --version`

**Comment by wishingwei** [comment]
@rhyolight 
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

I use the source code way and have seccussfully installed, in  nupic.core issue #684

**Comment by rhyolight** [comment]
@wishingwei Can you please [file a detailed bug report](https://github.com/numenta/nupic/issues/new?body=%3E%20What%20did%20you%20do%3F%20(steps%20to%20reproduce)%0A%0A%3E%20What%20happened%3F%20(actual%20results)%0A%0A%3E%20What%20should%20have%20happened%3F%20(expected%20results)%0A%0A%3E%20Additional%20Information%20(operating%20system%2C%20python%20version%2C%20NuPIC%20commit%20SHA%2C%20etc.)) that includes your environment details? It will help me track down this problem.

**Comment by chisophugis** [comment]
Running the recommended
```
pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.2.2-cp27-none-linux_x86_64.whl
pip install nupic
```

I see the same error as @wishingwei when running the `pip install nupic` command:

```
Downloading/unpacking nupic.bindings==0.2.2 (from nupic)
  Could not find any downloads that satisfy the requirement nupic.bindings==0.2.2 (from nupic)
Cleaning up...
No distributions at all found for nupic.bindings==0.2.2 (from nupic)
Storing debug log for failure in /home/sean/.pip/pip.log
```

Looking in the log file it mentions, there seems to be this relevant snippet:

```
Downloading/unpacking nupic.bindings==0.2.2 (from nupic)
  Getting page https://pypi.python.org/simple/nupic.bindings/
  URLs to search for versions for nupic.bindings==0.2.2 (from nupic):
  * https://pypi.python.org/simple/nupic.bindings/0.2.2
  * https://pypi.python.org/simple/nupic.bindings/
  Getting page https://pypi.python.org/simple/nupic.bindings/0.2.2
  Could not fetch URL https://pypi.python.org/simple/nupic.bindings/0.2.2: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/nupic.bindings/0.2.2 when looking for download links for nupic.bindings==0.2.2 (from nupic)
  Analyzing links from page https://pypi.python.org/simple/nupic.bindings/
    Skipping link https://pypi.python.org/packages/2.7/n/nupic.bindings/nupic.bindings-0.1.3-py2.7-macosx-10.9-intel.egg#md5=0c6937f6be30e8fa173de03d5f9917c0 (from https://pypi.python.org/simple/nupic.bindings/); unknown archive format: .egg
    Skipping https://pypi.python.org/packages/2.7/n/nupic.bindings/nupic.bindings-0.1.5-cp27-none-macosx_10_10_intel.whl#md5=9fd10771e643b2119b3bce525d64620b (from https://pypi.python.org/simple/nupic.bindings/) because it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/2.7/n/nupic.bindings/nupic.bindings-0.1.5-py2.7-linux-x86_64.egg#md5=8a46c12814fd1bd58384e0303b8073c2 (from https://pypi.python.org/simple/nupic.bindings/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/n/nupic.bindings/nupic.bindings-0.1.5-py2.7-macosx-10.9-intel.egg#md5=d0ded6e0e82e136bcadadd635eff6279 (from https://pypi.python.org/simple/nupic.bindings/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/n/nupic.bindings/nupic.bindings-0.2-py2.7-linux-x86_64.egg#md5=644fc96dfa617b61c952e13d2d82ba62 (from https://pypi.python.org/simple/nupic.bindings/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/n/nupic.bindings/nupic.bindings-0.2-py2.7-macosx-10.9-intel.egg#md5=15771c340dce2a19bc9c7715467aa8ba (from https://pypi.python.org/simple/nupic.bindings/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/n/nupic.bindings/nupic.bindings-0.2.1-py2.7-linux-x86_64.egg#md5=064dd5ea07c477c411100c46b618f05c (from https://pypi.python.org/simple/nupic.bindings/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/n/nupic.bindings/nupic.bindings-0.2.1-py2.7-macosx-10.9-intel.egg#md5=5f56ad3d2d8d6e753d7c5954d8ef757f (from https://pypi.python.org/simple/nupic.bindings/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/n/nupic.bindings/nupic.bindings-0.2.2-py2.7-linux-x86_64.egg#md5=8bfe2d7c20433b584148b4e798030f28 (from https://pypi.python.org/simple/nupic.bindings/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/n/nupic.bindings/nupic.bindings-0.2.2-py2.7-macosx-10.9-intel.egg#md5=f10665bb02d113e6c1f7d742420291ed (from https://pypi.python.org/simple/nupic.bindings/); unknown archive format: .egg
    Skipping https://pypi.python.org/packages/cp27/n/nupic.bindings/nupic.bindings-0.1.3-cp27-none-macosx_10_9_intel.whl#md5=4eb0138e25c7ed26cd949f9a43fbb9e1 (from https://pypi.python.org/simple/nupic.bindings/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp27/n/nupic.bindings/nupic.bindings-0.1.5-cp27-none-macosx_10_9_intel.whl#md5=f2e15fb2eeb0d28b1b3116a73bcaca04 (from https://pypi.python.org/simple/nupic.bindings/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp27/n/nupic.bindings/nupic.bindings-0.2-cp27-none-macosx_10_9_intel.whl#md5=48e66b798358e8e0c11f7cd00a42137a (from https://pypi.python.org/simple/nupic.bindings/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp27/n/nupic.bindings/nupic.bindings-0.2.1-cp27-none-macosx_10_9_intel.whl#md5=641f1ebcd966933a6b19bdb9c47c2442 (from https://pypi.python.org/simple/nupic.bindings/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp27/n/nupic.bindings/nupic.bindings-0.2.2-cp27-none-macosx_10_9_intel.whl#md5=2c02ceb6cd981572d9146c5f5b17cb9d (from https://pypi.python.org/simple/nupic.bindings/) because it is not compatible with this Python
  Could not find any downloads that satisfy the requirement nupic.bindings==0.2.2 (from nupic)
Cleaning up...
No distributions at all found for nupic.bindings==0.2.2 (from nupic)
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 304, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for nupic.bindings==0.2.2 (from nupic)
```

The root cause seems to be that it is not finding the wheel on s3 (even though it installed successfully from the previous command).

**Comment by chisophugis** [comment]
A workaround is to install both together in the same pip invocation:

```
pip install --allow-all-external https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.2.2-cp27-none-linux_x86_64.whl nupic
```

(I don't think the --allow-all-external is needed; that is just cruft from a previous invocation; for the sake of posterity I'm pasting the exact command that worked for me)

**Comment by RCinna** [comment]
I'm working on Ubuntu 15.10. I have the same issue after following the instructions on 
The first line command works well : 

     Successfully installed nupic.bindings pytest-cov numpy pytest-xdist pytest cov-core execnet py coverage apipkg
     Cleaning up...
This is the <i>pip install nupic</i> which has failed

    Downloading/unpacking nupic.bindings==0.2.2 (from nupic)
    Could not find any downloads that satisfy the requirement nupic.bindings==0.2.2 (from nupic)
    Cleaning up...
    No distributions at all found for nupic.bindings==0.2.2 (from nupic)
    Storing debug log for failure in /home/cannelle/.pip/pip.log

But importing nupic or nupic.bindings or pkg_resources in a python project is working good : 

    >>> import nupic, sys
    >>> print 'nupic' in sys.modules
    True

I'm dealing with that without installing nupic.core. In the "Compiling NuPic on Ubuntu 14 LTS"  video, it seems nupic.core have to be installed&build before nupic, but in "Installing NuPic on Ubuntu 14 LTS" video, tests scripts has been launch without nupic.core (not working for me). I'm not sure I've understood the all thing. nupic is python package, working on the nupic.core C++ software ?

**Comment by rhyolight** [comment]
The "installing" videos try to install from binary files, which sometimes
do not work, so folks have to resort to the "compiling" videos. Those
usually work, but require many more steps.

The nupic.core project is a C++ program with a Python SWiG extension that
also gets built into a python module called "nupic.bindings". And yes,
NuPIC is entirely Python, but depends upon the "nupic.bindings" package
being installed so it can call into the C++ library.


---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by kleineLi** [comment]
Hi! Help me, please!
I have run into this problem too, when running the following (as you noted above, mine is nupic.bindings -0.2.2)

pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.2.2-cp27-none-linux_x86_64.whl --user

![image](https://cloud.githubusercontent.com/assets/10851840/11446815/51d9afd6-955e-11e5-9fac-352f6a674d3c.png)

I don't know how to fix it.

**Comment by gades** [comment]
Problem on Ubuntu 15.10
```
hades@msi:~$ pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.2.2-cp27-none-linux_x86_64.whl
Downloading/unpacking https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.2.2-cp27-none-linux_x86_64.whl
  Downloading nupic.bindings-0.2.2-cp27-none-linux_x86_64.whl (15.7MB): 15.7MB downloaded
Downloading/unpacking pytest-xdist==1.8 (from nupic.bindings==0.2.2)
  Downloading pytest-xdist-1.8.zip
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 304, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 293, in run_egg_info
    logger.notify('Running setup.py (path:%s) egg_info for package %s' % (self.setup_py, self.name))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 266, in setup_py
    import setuptools
  File "/usr/share/python-wheels/setuptools-18.4-py2.py3-none-any.whl/setuptools/__init__.py", line 12, in <module>
    from setuptools.extension import Extension
  File "/usr/share/python-wheels/setuptools-18.4-py2.py3-none-any.whl/setuptools/extension.py", line 8, in <module>
  File "/usr/share/python-wheels/setuptools-18.4-py2.py3-none-any.whl/setuptools/dist.py", line 21, in <module>
AttributeError: 'module' object has no attribute 'packaging'

Storing debug log for failure in /tmp/tmp_q6UMc
```

Problem on OS X
```
Downloading/unpacking nupic.bindings==0.2.2 (from nupic)
  Could not find any downloads that satisfy the requirement nupic.bindings==0.2.2 (from nupic)
  Some externally hosted files were ignored (use --allow-external nupic.bindings to allow).
Cleaning up...
No distributions at all found for nupic.bindings==0.2.2 (from nupic)
Storing debug log for failure in /Users/hades/.pip/pip.log
(nupic)MacBook-Pro-Hades:/ hades$ 
```

**Comment by rhyolight** [comment]
@kleineLi I don't know what causes this problem, but I know that compiling from source code is the only workaround: https://www.youtube.com/watch?v=BrnPQJKpcWo

**Comment by FlyingSpringrol** [comment]
@chisophugis your workaround worked for me! Working on Ubuntu 15.10.
