### ISSUE TITLE
After NuPic install, failure to run hotgym.py correctly on Mac OSX

### ISSUE THREAD

**Issue by oebrooks** [numenta/nupic#3192]
After installing NuPic on my macbook with instruction from the youtube video, all tests passed or skipped, but the hotgym.py program does not run correctly. I receive the following error messages:

```
ERR:  Unable to create region Classifier of type SDRClassifierRegion [/Users/travis/build/numenta/nupic.core/src/nupic/engine/RegionImplFactory.cpp line 263]
Traceback (most recent call last):
  File "./hotgym.py", line 97, in <module>
    runHotgym()
  File "./hotgym.py", line 68, in runHotgym
    model = createModel()
  File "./hotgym.py", line 63, in createModel
    return ModelFactory.create(model_params.MODEL_PARAMS)
  File "/Users/Owen/Library/Python/2.7/lib/python/site-packages/nupic/frameworks/opf/modelfactory.py", line 80, in create
    return modelClass(**modelConfig['modelParams'])
  File "/Users/Owen/Library/Python/2.7/lib/python/site-packages/nupic/frameworks/opf/clamodel.py", line 213, in __init__
    clParams, anomalyParams)
  File "/Users/Owen/Library/Python/2.7/lib/python/site-packages/nupic/frameworks/opf/clamodel.py", line 1167, in __createCLANetwork
    n.addRegion("Classifier", "py.%s" % str(clRegionName), json.dumps(clParams))
  File "/Users/Owen/Library/Python/2.7/lib/python/site-packages/nupic/engine/__init__.py", line 665, in addRegion
    engine.Network.addRegion(self, name, nodeType, nodeParams)
  File "/Users/Owen/Library/Python/2.7/lib/python/site-packages/nupic/bindings/engine_internal.py", line 1087, in addRegion
    return _engine_internal.Network_addRegion(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'verbosity'
```

computer information:
late 2008 13" macbook
OS X Yosemite 10.10.5
Python version 2.7.10

**Comment by rhyolight** [comment]
@oebrooks Did you install from binary using `pip` or did you compile locally from source code?

**Comment by rhyolight** [comment]
This might be caused by https://github.com/numenta/nupic/pull/3166

**Comment by rhyolight** [comment]
Ok, I know what the problem is. @oebrooks you probably installed from binary, which installed NuPIC at [Release 0.5.4](https://github.com/numenta/nupic/tree/0.5.4), but you are running the hotgym code from the master branch, which has diverged from this release (it is ahead, and #3166 changed something in the hotgym code). 

All you have to do is go to your checkout directory and checkout the source code from the 0.5.4 tag like this to get the right version of the example code to match your binary installation. 

    git checkout 0.5.4

**Comment by oebrooks** [comment]
Thank you. Hotgym.py runs properly now.
