### ISSUE TITLE
nupic.core compilation failed

### ISSUE THREAD

**Issue by RCinna** [numenta/nupic#2769]
I'm working on Ubuntu 15.10.
I have same issue as #2651 following the installation step from binary.
Then I tried to install from source, so I followed the "Compiling NuPic on Ubuntu 14 LTS" video : 
    
    git clone https://github.com/numenta/nupic.core.git
    pip install -r bindings/py/requirements.txt
    cmake $NUPIC_CORE -DCMAKE_INSTALL_PREFIX=../release

Results seems to be okey : 

    -- The CXX compiler identification is GNU 5.2.1
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- checking for module 'capnp'
    --   found capnp, version 0.5.3
    -- Found CAPNP: /usr/local/include  
    Doing a local build
    -- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.10", minimum required is "2.7")
    GNU gold (GNU Binutils for Ubuntu 2.25.1) 1.11
    Copyright (C) 2014 Free Software Foundation, Inc.
    This program is free software; you may redistribute it under the terms of
    the GNU General Public License version 3 or (at your option) a later version.
    This program has absolutely no warranty.
    Using ld.gold as LINKER.
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.10")
    -- PYTHON_EXECUTABLE   = /usr/bin/python2.7
    -- PYTHON_INCLUDE_DIRS = /usr/include/python2.7
    -- PYTHON_LIBRARIES    = /usr/lib/x86_64-linux-gnu/libpython2.7.so
    -- CAPNP_DEFINITIONS   =
    -- CAPNP_INCLUDE_DIRS  = /usr/local/include
    -- CAPNP_LIBRARIES     = /usr/local/lib/libkj.a;/usr/local/lib/libcapnp.a;/usr/local/lib/libcapnpc.a
    -- CAPNP_LIBRARIES_LITE=
    -- Configuring done
    -- Generating done
    -- Build files have been written to: ${HOME}/nupic.core/build/scripts

But the <i>make<i> part does not pass, in the final step (98% complete) I have : 
    
    /tmp/ccZmJOOl.ltrans31.ltrans.o: In function `nupic::FractionTest::~FractionTest() [clone .lto_priv.273]':
    <artificial>:(.text+0x2f): undefined reference to `nupic::Tester::~Tester()'
    collect2: error: ld returned 1 exit status
    src/CMakeFiles/unit_tests.dir/build.make:1125: recipe for target 'src/unit_tests' failed
    make[2]: *** [src/unit_tests] Error 1
    CMakeFiles/Makefile2:626: recipe for target 'src/CMakeFiles/unit_tests.dir/all' failed
    make[1]: *** [src/CMakeFiles/unit_tests.dir/all] Error 2
    Makefile:136: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by rhyolight** [comment]
@RCinna First of all, sorry it has taken so long for a response. 

2nd, your problem may be due to NuPIC and NuPIC Core being out of sync with each other, which has been the case for the past several months. To confirm that this is the case checkout the following commit in NuPIC core:

```sh
cd $NUPIC_CORE
git checkout 392bc1c54e5aae8bc6ec76df1e534c6668e67fc4
```

Then try compiling again. Please let me know if using that specific SHA works?
